import type { CSSProperties } from "react";
import type {
  AgentResponse,
  RcaAdvisory,
  RcaExplanationEntry,
  RcaExplanationView,
} from "../api/types";
import { card, muted } from "../styles";

/**
 * Pure UI join (no I/O): pair each RCA `AgentResponse` (`extra.rca`) with its index-aligned grounded
 * advisory (`extra.rcaExplanation`), keeping only the RCAs that actually carry a non-empty advisory.
 *
 * An empty/absent advisory is fail-closed by construction on the backend (the keyless in-boundary
 * edge was UNCONFIGURED / below the confidence floor / ungrounded), so the console simply renders
 * nothing for it — the pure RCA result stands on its own. Kept pure so it is unit-testable without a
 * network or DOM, mirroring the house rule that derivations are pure functions.
 */
export function selectRcaExplanations(
  rca: readonly AgentResponse[] | null | undefined,
  explanations: readonly RcaExplanationEntry[] | null | undefined,
): RcaExplanationView[] {
  if (!rca || !explanations) return [];
  const views: RcaExplanationView[] = [];
  for (let i = 0; i < rca.length; i += 1) {
    const advisory = explanations[i]?.advisory?.trim() ?? "";
    if (advisory.length === 0) continue;
    views.push({ rca: rca[i], advisory });
  }
  return views;
}

/**
 * Pure adapter: turn the backend's persisted, bounded `RcaAdvisory[]` read model (from
 * `GET /api/workloads/{workload}/rca-explanations`) into the `RcaExplanationView[]` this panel
 * renders. The read model already carries ONLY grounded/non-empty advisories, so this just shapes
 * each into the panel's `{ rca, advisory }` view. The advisory's grounding evidence — the bounded
 * `findings`/`risks`/`recommendations` + `sourceReferences` it was grounded on — is carried through
 * so the panel can SHOW exactly what each advisory is grounded on (MED-5). The display-only
 * `AgentResponse` fields the panel does not use (inputSummary/nextActions) are filled empty.
 */
export function advisoriesToViews(
  advisories: readonly RcaAdvisory[] | null | undefined,
): RcaExplanationView[] {
  if (!advisories) return [];
  const views: RcaExplanationView[] = [];
  for (const advisory of advisories) {
    const text = advisory.advisory?.trim() ?? "";
    if (text.length === 0) continue;
    views.push({
      rca: {
        agentName: advisory.agentName,
        taskType: advisory.taskType,
        inputSummary: "",
        findings: advisory.findings ?? [],
        risks: advisory.risks ?? [],
        recommendations: advisory.recommendations ?? [],
        sourceReferences: advisory.sourceReferences,
        confidence: advisory.confidence,
        nextActions: [],
        generatedAt: advisory.generatedAt,
      },
      advisory: text,
    });
  }
  return views;
}

/**
 * Advisory-only, grounded RCA explanation panel (issue #54). Renders a natural-language explanation
 * of an auto-RCA, generated by an in-boundary LLM and grounded STRICTLY on the RCA's already-cited
 * evidence. It is CLEARLY labelled as an AI advisory ("human disposes") and always shows the cited
 * evidence alongside it so an operator can verify the narrative against the sources. It renders
 * nothing when no grounded explanation is available (graceful, fail-closed).
 */
export function RcaExplanation({ views }: { views: RcaExplanationView[] }) {
  if (views.length === 0) return null;

  return (
    <section aria-label="RCA advisory explanations" style={{ display: "grid", gap: 12 }}>
      <h3 style={{ margin: 0, fontSize: 15 }}>🤖 RCA advisory — AI-generated, grounded on evidence</h3>
      <p style={{ ...muted, margin: 0 }}>
        AI proposes, a human disposes. Each explanation is advisory only, generated in-boundary and
        grounded strictly on the cited evidence below — it is never a remediation and is never
        applied automatically.
      </p>
      {views.map((view, i) => (
        <article
          key={`${view.rca.agentName}:${view.rca.generatedAt}:${i}`}
          aria-label={`RCA advisory for ${view.rca.taskType}`}
          style={card}
        >
          <div style={{ display: "flex", alignItems: "baseline", gap: 8, flexWrap: "wrap" }}>
            <span style={badge}>AI ADVISORY</span>
            <code style={{ fontSize: 11, color: "#5f6368" }}>{view.rca.agentName}</code>
            <span style={{ fontSize: 12, color: "#5f6368", fontVariantNumeric: "tabular-nums" }}>
              confidence <strong>{view.rca.confidence.toFixed(2)}</strong>
            </span>
          </div>

          <p style={{ margin: "8px 0 0", fontSize: 13, color: "#3c4043" }}>{view.advisory}</p>

          <div style={{ marginTop: 10, fontSize: 12 }}>
            <div style={{ fontWeight: 600, color: "#3c4043" }}>Cited evidence</div>
            <EvidenceList label="Findings" items={view.rca.findings} />
            <EvidenceList label="Risks" items={view.rca.risks} />
            <EvidenceList label="Recommendations" items={view.rca.recommendations} />
            {view.rca.sourceReferences.length === 0 ? (
              <p style={{ margin: "2px 0 0", color: "#a50e0e" }}>
                ⚠ No evidence cited — treat as unverified (fail-closed).
              </p>
            ) : (
              <ul style={{ margin: "2px 0 0", paddingLeft: 18 }}>
                {view.rca.sourceReferences.map((ref, j) => (
                  <li key={`${ref.kind}:${ref.id}:${j}`} style={{ marginBottom: 2 }}>
                    <span style={{ color: "#5f6368" }}>{ref.kind}</span>{" "}
                    <code style={{ fontSize: 11 }}>{ref.id}</code>
                    {ref.detail && <span style={{ color: "#5f6368" }}> — {ref.detail}</span>}
                  </li>
                ))}
              </ul>
            )}
          </div>
        </article>
      ))}
    </section>
  );
}

/**
 * Render one bounded, cited evidence list (findings/risks/recommendations) the advisory is grounded
 * on. Text is React-escaped by default (NO dangerouslySetInnerHTML). Renders nothing when empty so a
 * category the RCA did not populate does not clutter the panel.
 */
function EvidenceList({ label, items }: { label: string; items: readonly string[] }) {
  if (items.length === 0) return null;
  return (
    <div style={{ marginTop: 4 }}>
      <div style={{ color: "#5f6368", fontWeight: 600 }}>{label}</div>
      <ul style={{ margin: "2px 0 0", paddingLeft: 18 }}>
        {items.map((item, k) => (
          <li key={`${label}:${k}`} style={{ marginBottom: 2, color: "#3c4043" }}>
            {item}
          </li>
        ))}
      </ul>
    </div>
  );
}

const badge: CSSProperties = {
  display: "inline-block",
  border: "1px solid #7b1fa2",
  color: "#7b1fa2",
  borderRadius: 4,
  padding: "1px 6px",
  fontSize: 11,
  fontWeight: 700,
  textTransform: "uppercase",
};
